### ISSUE TITLE
Fails with perls <= 5.12.5

### ISSUE THREAD

**Issue by andk** [arunbear/Minions#2]
As per subject. Best illustrated with the matrix:

http://matrix.cpantesters.org/?dist=Minions%200.000007

Sample fail report:

http://www.cpantesters.org/cpan/report/fd06aa74-b7cf-11e5-8e1d-99c4fcd2507e

If this is intentional, it would be cool if you could declare your requirement. That way the intentional FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

HTH && Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by arunbear** [comment]
This was fixed in 0.000008
